/*
 * main.c  –  Vehicle GPS Tracker  (STM32L0538-DISCO)
 *
 * Hardware connections
 * ───────────────────
 *  I2C1  PB6/PB7  → ESP32 (GPS over I2C slave, addr 0x08)
 *  UART1 PA9/PA10 → SIM800L GSM module
 *  SPI2  PB13-15  → W25Qxx external flash  (CS = PB0)
 *  SPI1            → E-Paper display  (already working)
 *
 * Behaviour
 * ─────────
 *  Every 30 s (TIM2 interrupt):
 *    1. Read GPS string from ESP32 over I2C.
 *    2. If GSM signal available  → send SMS immediately.
 *       Else                     → store in flash circular buffer (max 5).
 *    3. Whenever signal returns  → flush all buffered locations via SMS,
 *                                   then clear the buffer.
 */

/*PB6     ------> I2C1_SCL
  PB7     ------> I2C1_SDA*/
/* PA9  ------> USART1_TX
   PA10 ------> USART1_RX*/
/**SPI2 GPIO Configuration
  PB13     ------> SPI2_SCK
  PB14     ------> SPI2_MISO
  PB15     ------> SPI2_MOSI  */

#include "main.h"
#include "SIM800L.h"
#include "flash.h"
#include "gps_storage.h"
#include "EPD.h"

/* ── User configuration ─────────────────────────────────────────────────── */
#define PHONE_NUMBER      "+918688558093"
#define ESP32_I2C_ADDR    (0x08 << 1)   /* 7-bit addr 0x08, shifted for HAL */
#define GPS_STR_LEN        32            /* max bytes to request from ESP32   */

/* ── HAL handles (generated by CubeMX) ──────────────────────────────────── */
I2C_HandleTypeDef  hi2c1;
SPI_HandleTypeDef  hspi1;
SPI_HandleTypeDef  hspi2;
TIM_HandleTypeDef  htim2;
UART_HandleTypeDef huart1;

/* ── Shared state ────────────────────────────────────────────────────────── */
volatile uint8_t  send_sms_flag = 0;   /* set every 30 s by TIM2 ISR        */
volatile uint32_t seconds       = 0;
//extern volatile uint8_t  network_ok  ;   /* updated by Check_Network_Status()  */


/* ── Forward declarations ───────────────────────────────────────────────── */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_SPI1_Init(void);
static void MX_SPI2_Init(void);
static void MX_TIM2_Init(void);
static void MX_USART1_UART_Init(void);

/* ── Private helpers ────────────────────────────────────────────────────── */

/**
 * @brief  Ask the ESP32 for the latest GPS string via I2C.
 * @param  buf     Buffer to receive the null-terminated location string.
 * @param  buflen  Size of buf.
 * @return 1 if a valid-looking location was received, 0 on error.
 */
static uint8_t GPS_Read_From_ESP32(char *buf, uint16_t buflen)
{
    uint8_t tmp[GPS_STR_LEN];
    memset(tmp, 0, sizeof(tmp));

    HAL_StatusTypeDef st = HAL_I2C_Master_Receive(
            &hi2c1, ESP32_I2C_ADDR, tmp, GPS_STR_LEN - 1, HAL_MAX_DELAY);

    if (st != HAL_OK)
        return 0;

    tmp[GPS_STR_LEN - 1] = '\0';

    /* Minimal validity check: must contain a comma (lat,lon format) */
//    if (strchr((char *)tmp, ',') == NULL)
//        return 0;

    strncpy(buf, (char *)tmp, buflen - 1);
    buf[buflen - 1] = '\0';
    return 1;
}

/**
 * @brief  Flush all buffered GPS locations to SMS, then clear the buffer.
 */
static void Flush_Stored_Locations(void)
{
    char locs[GPS_MAX_ENTRIES][GPS_SLOT_SIZE];
    uint8_t n = GPS_Storage_ReadAll(locs);

    if (n == 0)
        return;

    char sms[160];
    /* Send one SMS per stored location to keep each message short */
    for (uint8_t i = 0; i < n; i++)
    {
        snprintf(sms, sizeof(sms), "GPS(stored %u/%u): %s", i + 1, n, locs[i]);
        SIM800_SendSMS(PHONE_NUMBER, sms);
        //EPD_Print(sms);
        HAL_Delay(3000);   /* give GSM module breathing room between SMSes  */
    }

    GPS_Storage_Clear();
    EPD_Print("Buffer flushed");
}

/* ── Application entry point ─────────────────────────────────────────────── */

int main(void)
{
    /* --- MCU init -------------------------------------------------------- */
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_SPI1_Init();
    MX_SPI2_Init();
    MX_TIM2_Init();
    MX_USART1_UART_Init();
    EPD_Init();
    EPD_Print("EPD : OK");
    /* --- Subsystem init -------------------------------------------------- */
    GPS_Storage_Init();           /* restore circular buffer state from flash */
    EPD_Print("FLASH : OK");
    /* Start 1-second TIM2 tick */
    HAL_TIM_Base_Start_IT(&htim2);
    EPD_Print("TIMER : OK");
    HAL_Delay(1000);
    /* --- Main loop ------------------------------------------------------- */

    while (1)
    {
        if (!send_sms_flag)
        {
            HAL_PWR_EnterSLEEPMode(PWR_MAINREGULATOR_ON, PWR_SLEEPENTRY_WFI);
            continue;
        }

        /* ── 30-second tick ───────────────────────────────────────────── */
        send_sms_flag = 0;

        /* 1. Read GPS from ESP32 */
        char location[GPS_SLOT_SIZE];
        uint8_t gps_ok = GPS_Read_From_ESP32(location, sizeof(location));

        if (!gps_ok)
        {
            EPD_Print("No GPS fix");
            /* Nothing to store or send — skip this cycle */
            continue;
        }

        EPD_Print(location);

        /* 2. Check GSM signal */
        Check_Network_Status();

        if (network_ok)
        {
            /* 2a. Signal present — flush buffer first (if any), then send live */
            if (GPS_Storage_Count() > 0)
            {
                EPD_Print("Flushing buffer...");
                Flush_Stored_Locations();
            }

            char sms[160];
            snprintf(sms, sizeof(sms), "GPS: %s", location);
            SIM800_SendSMS(PHONE_NUMBER, sms);
        }
        else
        {
            /* 2b. No signal — store in flash circular buffer */
            GPS_Storage_Save(location);

            char disp[48];
            snprintf(disp, sizeof(disp), "Stored %u/5", GPS_Storage_Count());
            EPD_Print(disp);
        }
    }
}

/* ── TIM2 ISR — fires every 1 second ────────────────────────────────────── */

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM2)
    {
        seconds++;
        if (seconds >= 30)
        {
            send_sms_flag = 1;
            seconds       = 0;
        }
    }
}

//void TIM2_IRQHandler(void)
//{
//    HAL_TIM_IRQHandler(&htim2);
//}

/* ── Clock & peripheral init (unchanged from CubeMX output) ─────────────── */

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef      RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef      RCC_ClkInitStruct = {0};
    RCC_PeriphCLKInitTypeDef PeriphClkInit    = {0};

    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    RCC_OscInitStruct.OscillatorType      = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState            = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState        = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource       = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLMUL          = RCC_PLLMUL_4;
    RCC_OscInitStruct.PLL.PLLDIV          = RCC_PLLDIV_2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
        Error_Handler();

    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                     | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
        Error_Handler();

    PeriphClkInit.PeriphClockSelection  = RCC_PERIPHCLK_USART1 | RCC_PERIPHCLK_I2C1;
    PeriphClkInit.Usart1ClockSelection  = RCC_USART1CLKSOURCE_PCLK2;
    PeriphClkInit.I2c1ClockSelection    = RCC_I2C1CLKSOURCE_PCLK1;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
        Error_Handler();
}

static void MX_I2C1_Init(void)
{
    hi2c1.Instance             = I2C1;
    hi2c1.Init.Timing          = 0x00B07CB4;
    hi2c1.Init.OwnAddress1     = 0;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.OwnAddress2     = 0;
    hi2c1.Init.OwnAddress2Masks= I2C_OA2_NOMASK;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK)
        Error_Handler();
    if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK)
        Error_Handler();
    if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK)
        Error_Handler();
}

static void MX_SPI1_Init(void)
{
    hspi1.Instance               = SPI1;
    hspi1.Init.Mode              = SPI_MODE_MASTER;
    hspi1.Init.Direction         = SPI_DIRECTION_2LINES;
    hspi1.Init.DataSize          = SPI_DATASIZE_8BIT;
    hspi1.Init.CLKPolarity       = SPI_POLARITY_LOW;
    hspi1.Init.CLKPhase          = SPI_PHASE_1EDGE;
    hspi1.Init.NSS               = SPI_NSS_SOFT;
    hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_16;
    hspi1.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    hspi1.Init.TIMode            = SPI_TIMODE_DISABLE;
    hspi1.Init.CRCCalculation    = SPI_CRCCALCULATION_DISABLE;
    hspi1.Init.CRCPolynomial     = 7;
    if (HAL_SPI_Init(&hspi1) != HAL_OK)
        Error_Handler();
}

static void MX_SPI2_Init(void)
{
    hspi2.Instance               = SPI2;
    hspi2.Init.Mode              = SPI_MODE_MASTER;
    hspi2.Init.Direction         = SPI_DIRECTION_2LINES;
    hspi2.Init.DataSize          = SPI_DATASIZE_8BIT;
    hspi2.Init.CLKPolarity       = SPI_POLARITY_LOW;
    hspi2.Init.CLKPhase          = SPI_PHASE_1EDGE;
    hspi2.Init.NSS               = SPI_NSS_SOFT;
    hspi2.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_8;
    hspi2.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    hspi2.Init.TIMode            = SPI_TIMODE_DISABLE;
    hspi2.Init.CRCCalculation    = SPI_CRCCALCULATION_DISABLE;
    hspi2.Init.CRCPolynomial     = 7;
    if (HAL_SPI_Init(&hspi2) != HAL_OK)
        Error_Handler();
}

static void MX_TIM2_Init(void)
{
    TIM_ClockConfigTypeDef  sClockSourceConfig = {0};
    TIM_MasterConfigTypeDef sMasterConfig      = {0};

    /*
     * TIM2 @ 32 MHz (PLLCLK), prescaler = 31999, period = 999
     * → interrupt every  (31999+1)*(999+1) / 32 000 000 = 1.000 s
     */
    htim2.Instance               = TIM2;
    htim2.Init.Prescaler         = 31999;
    htim2.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim2.Init.Period            = 999;
    htim2.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
    if (HAL_TIM_Base_Init(&htim2) != HAL_OK)
        Error_Handler();

    sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
    if (HAL_TIM_ConfigClockSource(&htim2, &sClockSourceConfig) != HAL_OK)
        Error_Handler();

    sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
    sMasterConfig.MasterSlaveMode     = TIM_MASTERSLAVEMODE_DISABLE;
    if (HAL_TIMEx_MasterConfigSynchronization(&htim2, &sMasterConfig) != HAL_OK)
        Error_Handler();

    HAL_NVIC_SetPriority(TIM2_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(TIM2_IRQn);
}

static void MX_USART1_UART_Init(void)
{
    huart1.Instance            = USART1;
    huart1.Init.BaudRate       = 9600;          /* SIM800L default baud      */
    huart1.Init.WordLength     = UART_WORDLENGTH_8B;
    huart1.Init.StopBits       = UART_STOPBITS_1;
    huart1.Init.Parity         = UART_PARITY_NONE;
    huart1.Init.Mode           = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl      = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling   = UART_OVERSAMPLING_16;
    huart1.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
    huart1.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
    if (HAL_UART_Init(&huart1) != HAL_OK)
        Error_Handler();
}

static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOH_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* Flash CS (PB0), EPD pins (PB2, PB11) – default HIGH (deselected) */
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_12 | GPIO_PIN_2 | GPIO_PIN_11, GPIO_PIN_SET);

    GPIO_InitStruct.Pin   = GPIO_PIN_12 | GPIO_PIN_2 | GPIO_PIN_11;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    /* PA15 – EPD CS */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_15, GPIO_PIN_SET);
    GPIO_InitStruct.Pin   = GPIO_PIN_15;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}

void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    (void)file; (void)line;
}
#endif
